Repository ONLYOFFICE-QA/onlyoffice_documentserver_testing_framework, pull requests merged in 2024-06, with the labels that each got.

#1490 Release v2.17.0
  CHANGELOG.md
  Gemfile.lock
  lib/onlyoffice_documentserver_testing_framework/version.rb
Labels: release

#1494 Actualzie language list for DocumentServer v8.1
  .rubocop_todo.yml
  CHANGELOG.md
  lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
  lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions/languages_list/doc_test_site_languages_after_8_1.list
Labels: Changes

#1498 Simplify `DocumentServerVersion#supported_languages` method
  .rubocop_todo.yml
  CHANGELOG.md
  lib/onlyoffice_documentserver_testing_framework/test_instance_docs/doc_test_site_functions.rb
  spec/doc_test_site_functions/supported_languages_spec.rb
Labels: enhancement
